version: '2.4'
services:
  db:
    image: postgres:latest
    container_name: year_percentage_tg_bot_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: year_percentage_bot_db
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
